import { Router, Request, Response } from 'express';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { getUserCount, createFirstSuperAdmin } from '../prismaService';
import { logActivity, loadDB, saveDB } from '../store';

const router = Router();
const JWT_SECRET = process.env.JWT_SECRET || 'unique-sweets-secret-key-2026';

// Check if setup is required
router.get('/status', async (req: Request, res: Response) => {
  try {
    const userCount = await getUserCount();
    const isSetupRequired = userCount === 0;

    return res.json({
      isSetupRequired,
      userCount,
      message: isSetupRequired
        ? 'First-time setup wizard required.'
        : 'System setup is complete.',
    });
  } catch (error: any) {
    console.error('Error checking setup status:', error);
    return res.status(500).json({ error: 'Failed to check setup status.' });
  }
});

// Create the first Super Admin
router.post('/initialize', async (req: Request, res: Response) => {
  try {
    const userCount = await getUserCount();
    if (userCount > 0) {
      return res.status(400).json({
        error: 'First-time setup wizard is disabled. An administrator account already exists.',
      });
    }

    const name = String(req.body?.name || '').trim();
    const email = String(req.body?.email || '').trim().toLowerCase();
    const password = String(req.body?.password || '');
    const confirmPassword = String(req.body?.confirmPassword || '');

    if (!name || !name.trim()) {
      return res.status(400).json({ error: 'Full name is required.' });
    }

    if (!email || !email.trim()) {
      return res.status(400).json({ error: 'Email address is required.' });
    }

    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email.trim())) {
      return res.status(400).json({ error: 'Please enter a valid email address.' });
    }

    if (!password || password.length < 6) {
      return res.status(400).json({ error: 'Password must be at least 6 characters long.' });
    }

    if (password !== confirmPassword) {
      return res.status(400).json({ error: 'Passwords do not match.' });
    }

    // Secure bcrypt hash
    const salt = bcrypt.genSaltSync(10);
    const passwordHash = bcrypt.hashSync(password, salt);

    const superAdmin = await createFirstSuperAdmin({
      name: name.trim(),
      email: email.trim().toLowerCase(),
      passwordHash,
    });

    logActivity(
      superAdmin.id,
      superAdmin.name,
      'First-Time Setup Completed',
      'System Setup',
      `Super Admin created: ${superAdmin.email}`
    );

    const token = jwt.sign(
      {
        id: superAdmin.id,
        name: superAdmin.name,
        email: superAdmin.email,
        role: superAdmin.role,
      },
      JWT_SECRET,
      { expiresIn: '24h' }
    );

    return res.status(201).json({
      success: true,
      message: 'Super Admin account created successfully.',
      isSetupRequired: false,
      token,
      user: {
        id: superAdmin.id,
        name: superAdmin.name,
        email: superAdmin.email,
        role: superAdmin.role,
        isActive: superAdmin.isActive,
      },
    });
  } catch (error: any) {
    console.error('Error during initial setup:', error);
    return res.status(500).json({ error: 'Failed to create Super Admin account.' });
  }
});

// Purge test / audit records generated by automated E2E tests
router.post('/clean-audit-data', (req: Request, res: Response) => {
  try {
    const db = loadDB();

    const isAuditStr = (str: string | undefined) => {
      if (!str) return false;
      const l = str.toLowerCase();
      return (
        l.includes('audit supplier') ||
        l.includes('audit customer') ||
        l.includes('test audit category') ||
        l.includes('test audit kachori') ||
        l.includes('temporary clean product') ||
        l.includes('auditor cashier') ||
        l.includes('audit shift') ||
        l.includes('audit test') ||
        l.includes('automated test')
      );
    };

    // Clean Suppliers
    const testSupplierIds = new Set<string>();
    db.suppliers = (db.suppliers || []).filter((s: any) => {
      if (isAuditStr(s.name) || isAuditStr(s.companyName)) {
        testSupplierIds.add(s.id);
        return false;
      }
      return true;
    });
    db.supplierLedgers = (db.supplierLedgers || []).filter((l: any) => !testSupplierIds.has(l.supplierId) && !isAuditStr(l.notes));

    // Clean Customers
    const testCustomerIds = new Set<string>();
    db.customers = (db.customers || []).filter((c: any) => {
      if (isAuditStr(c.name)) {
        testCustomerIds.add(c.id);
        return false;
      }
      return true;
    });
    db.customerLedgers = (db.customerLedgers || []).filter((l: any) => !testCustomerIds.has(l.customerId) && !isAuditStr(l.notes));

    // Clean Categories & Products
    const testCategoryIds = new Set<string>();
    db.categories = (db.categories || []).filter((cat: any) => {
      if (isAuditStr(cat.name)) {
        testCategoryIds.add(cat.id);
        return false;
      }
      return true;
    });

    const testProductIds = new Set<string>();
    db.products = (db.products || []).filter((p: any) => {
      if (isAuditStr(p.name) || testCategoryIds.has(p.categoryId)) {
        testProductIds.add(p.id);
        return false;
      }
      return true;
    });

    // Clean Sales & Purchases
    db.sales = (db.sales || []).filter((s: any) => {
      if (isAuditStr(s.cashierName) || isAuditStr(s.customerName) || (s.customerId && testCustomerIds.has(s.customerId))) {
        return false;
      }
      if (s.items && s.items.some((i: any) => testProductIds.has(i.productId) || isAuditStr(i.productName))) {
        return false;
      }
      return true;
    });

    db.purchases = (db.purchases || []).filter((p: any) => {
      if ((p.supplierId && testSupplierIds.has(p.supplierId)) || isAuditStr(p.supplierName)) {
        return false;
      }
      if (p.items && p.items.some((i: any) => testProductIds.has(i.productId) || isAuditStr(i.productName))) {
        return false;
      }
      return true;
    });

    // Clean Shifts
    db.cashShifts = (db.cashShifts || []).filter((sh: any) => {
      return !(isAuditStr(sh.cashierName) || isAuditStr(sh.notes) || isAuditStr(sh.varianceReason));
    });

    // Clean Adjustments, Transfers, Inventory Logs
    db.adjustments = (db.adjustments || []).filter((a: any) => !(testProductIds.has(a.productId) || isAuditStr(a.reason) || isAuditStr(a.adjustedByName)));
    db.transfers = (db.transfers || []).filter((t: any) => !(t.items && t.items.some((i: any) => testProductIds.has(i.productId) || isAuditStr(i.productName))));
    db.inventoryLogs = (db.inventoryLogs || []).filter((l: any) => !(testProductIds.has(l.productId) || isAuditStr(l.referenceNo) || isAuditStr(l.notes)));

    // Clean Recipes & Production Batches
    db.recipes = (db.recipes || []).filter((r: any) => !(testProductIds.has(r.productId) || isAuditStr(r.productName)));
    db.productionBatches = (db.productionBatches || []).filter((b: any) => !(testProductIds.has(b.productId) || isAuditStr(b.productName) || isAuditStr(b.operatorName)));

    // Clean Journal Entries
    db.journalEntries = (db.journalEntries || []).filter((j: any) => !(isAuditStr(j.narration) || isAuditStr(j.referenceNo) || isAuditStr(j.createdBy)));

    // Recalculate customer balances from remaining ledgers
    (db.customers || []).forEach((c: any) => {
      const cLedger = (db.customerLedgers || []).filter((l: any) => l.customerId === c.id);
      if (cLedger.length > 0) {
        c.outstandingBalance = cLedger[0].balanceAfter;
      } else {
        c.outstandingBalance = 0;
      }
    });

    // Recalculate supplier balances from remaining ledgers
    (db.suppliers || []).forEach((s: any) => {
      const sLedger = (db.supplierLedgers || []).filter((l: any) => l.supplierId === s.id);
      if (sLedger.length > 0) {
        s.outstandingBalance = sLedger[0].balanceAfter;
      } else {
        s.outstandingBalance = 0;
      }
    });

    // Recalculate financial bank account balances if only test transactions existed
    if ((db.sales || []).length === 0 && (db.expenses || []).length === 0 && (db.journalEntries || []).length === 0) {
      (db.bankAccounts || []).forEach((a: any) => {
        a.currentBalance = a.openingBalance || 0;
      });
    }

    saveDB();
    return res.json({ success: true, message: 'Audit & test data cleaned successfully.' });
  } catch (err: any) {
    return res.status(500).json({ error: err.message });
  }
});

export default router;
